# Generated by Django 4.2.2 on 2023-06-18 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hacks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hack',
            name='bookmarks',
        ),
        migrations.AlterField(
            model_name='hack',
            name='category',
            field=models.CharField(choices=[('choose your category', 'Choose Your Category'), ('beauty', 'Beauty'), ('household', 'Household'), ('health', 'Health'), ('cleaning', 'Cleaning'), ('others', 'Others')], default='Choose your category', max_length=50),
        ),
    ]
