# Generated by Django 4.2.2 on 2023-06-18 14:39

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('hacks', '0002_remove_hack_bookmarks_alter_hack_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='hack',
            name='ingredients',
            field=djrichtextfield.models.RichTextField(default='unknown', max_length=10000),
        ),
    ]
