# Generated by Django 4.2.2 on 2023-06-25 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("hacks", "0002_alter_comment_options_remove_comment_hack_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="hack",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="hacks.hack",
            ),
            preserve_default=False,
        ),
    ]
