# Generated by Django 4.2.2 on 2023-06-27 20:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hacks", "0003_comment_hack"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Bookmark",
        ),
    ]
