# Generated by Django 4.2.2 on 2023-06-30 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("hacks", "0004_delete_bookmark"),
    ]

    operations = [
        migrations.CreateModel(
            name="Like",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[("hack", "Hack"), ("comment", "Comment")],
                        default="hack",
                        max_length=50,
                    ),
                ),
                ("liked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "hack",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hacks.hack"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
