# Generated by Django 4.2.2 on 2023-07-04 12:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hacks", "0005_like"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="likehack",
            name="liked_hack",
        ),
        migrations.RemoveField(
            model_name="likehack",
            name="user",
        ),
        migrations.AlterField(
            model_name="hack",
            name="category",
            field=models.CharField(
                choices=[
                    ("Beauty", "Beauty"),
                    ("Household", "Household"),
                    ("Health", "Health"),
                    ("Cleaning", "Cleaning"),
                    ("Others", "Others"),
                ],
                default="Others",
                max_length=50,
            ),
        ),
        migrations.DeleteModel(
            name="LikeComment",
        ),
        migrations.DeleteModel(
            name="LikeHack",
        ),
    ]
